language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.18
  - DJANGO_VERSION=2.0.10
  - DJANGO_VERSION=2.1.5
# command to install dependencies
install:
  - pip install -r test_requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script: python runtests.py
